name: Publish

on:
  release:
    types:
      - published

env:
  NODE_VERSION: 18

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0 # zero stands for full checkout, which is required for semantic-release
          filter: blob:none # we don't need all blobs, only the full tree
          show-progress: false
          
      - uses: containerbase/internal-tools/setup@df03af281c3457391eeac44f4f994211cd17fb8b # v3.10.89
        with:
          checkout: false
          node-version: ${{ env.NODE_VERSION }}

      - name: Build
        run: pnpm run build

      - name: Publish
        run: pnpm publish --verbose --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
