name: Publish

on:
  release:
    types:
      - published

env:
  NODE_VERSION: 18

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: containerbase/internal-tools/setup@1512f33187f6f55360f519853e7b247084e2970f # v3.10.88
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build
        run: pnpm run build

      - name: Publish
        run: pnpm publish --verbose --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
