name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
  push:
    branches:
      - main

env:
  NODE_VERSION: 18

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04

    steps:
      - uses: containerbase/internal-tools/setup@1512f33187f6f55360f519853e7b247084e2970f # v3.10.88
        with:
          save-cache: true
          node-version: ${{ env.NODE_VERSION }}

      - run: pnpm build

      - run: pnpm eslint -f gha

      # TODO: add prettier
      # - run: pnpm prettier

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    name: test-${{ matrix.os }}

    steps:
      - uses: containerbase/internal-tools/setup@1512f33187f6f55360f519853e7b247084e2970f # v3.10.88
        with:
          save-cache: true
          node-version: ${{ env.NODE_VERSION }}

      - name: Test
        run: pnpm test
        shell: bash

      - name: Codecov
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          
      - name: Upload test results to Codecov
        if: true != cancelled() 
        uses: codecov/test-results-action@47f89e9acb64b76debcd5ea40642d25a4adced9f # v1.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

 # Catch-all required check for test matrix
  success:
    needs:
      - lint
      - test
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    if: always()
    steps:
      - name: Fail for failed or cancelled lint tests
        if: |
          needs.lint.result == 'failure' ||
          needs.lint.result == 'cancelled'
        run: exit 1

      - name: Fail for failed or cancelled test tests
        if: |
          needs.test.result == 'failure' ||
          needs.test.result == 'skipped'
        run: exit 1